#Drill #26
<img src="https://drive.google.com/uc?id=1y7J8HlclDc_200W1oYBVtr3l-66B_2hv" width="700">

#Expected Output
<img src="https://drive.google.com/uc?id=1HPkRafcIsT7vLp8_2rR5blhjblQZJ450" width="650">

In [0]:
# indexing 
import numpy as np
a = np.identity(5)
print('5th row in the 2-d array is:', a[4, :]) #indexing begin at 0
a[2, 4] = 100; #assiging value in the matrix
print(a)

print('-'*70)

#slicing
b = np.arange(20)
print(b[1:18:2]) #[startindex: endindex(exclusive) : step]

print('-'*70)

#Basic Operations
a = np.array([1, 2, 3, 4])
print(a + 1) #This adds 1 to each element in array a
print(a**2) #squares each element in array a

print('-'*70)

#Matrix Multiplication
c = np.diag([1, 2, 3, 4])
d = np.ones(4) + 1
print(c * d)

5th row in the 2-d array is: [0. 0. 0. 0. 1.]
[[  1.   0.   0.   0.   0.]
 [  0.   1.   0.   0.   0.]
 [  0.   0.   1.   0. 100.]
 [  0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   1.]]
----------------------------------------------------------------------
[ 1  3  5  7  9 11 13 15 17]
----------------------------------------------------------------------
[2 3 4 5]
[ 1  4  9 16]
----------------------------------------------------------------------
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


# Drill #27
<img src="https://drive.google.com/uc?id=1eH9ep0AX9B7t6841wqWzgF5Z_3yXfolK" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1s9igAQj39y7jp4u4kWQEYKy_Rh0bStH-" width="400">

In [0]:
uc = 'PYTHON ROCKS'

print(f"This is all uppercase - {uc}")

print(f"Now this is lowercase - {uc.lower()}")

uc_split = uc.split(' ')
print(f'I have split the string in two - {uc_split[0]} and {uc_split[1]}')

print(f'I am joining the split string again to get - {uc_split[0] + "really" + uc_split[1]}')

This is all uppercase - PYTHON ROCKS
Now this is lowercase - python rocks
I have split the string in two - PYTHON and ROCKS
I am joining the split string again to get - PYTHONreallyROCKS


# Drill #28
<img src="https://drive.google.com/uc?id=1uchcSeNEcXeL-a5uRNAte-tQduVcds-X" width="700"> //
<img src="https://drive.google.com/uc?id=16hZqIZ4GYCy-OWRVG4h1-M-_x__thrKt" width="700"> //
<img src="https://drive.google.com/uc?id=1Ktb4Wf0A82_aD_L0otp74o3lyIjQuXCn" width="700"> //

# Expected Output
<img src="https://drive.google.com/uc?id=1_GcsstP7aMtm1vAUh4k6AaK5kaWDqO7V" width="400">

In [0]:
# create a mapping of state to abbreviation

states = {
    'Uttar Pradesh' : 'UP',
    'Andhra Pradesh' : 'AP',
    'Telangana' : 'TL',
    'West Bengal' : 'WB',
    'Tamil Nadu' : 'TN'
   }
#create a basic set of states and some cities in them
cities = {
    'UP' : 'Kanpur',
    'TN' : 'Chennai',
    'WB' : 'Kolkata'
}
# add some more cities
cities['AP'] = 'Visakhapatnam'
cities['TL'] = 'Hyerabad'
#print out some cities
print('-'*10)
print('UP state has:', cities['UP'])
print('AP state has:', cities['AP'])

#print some cities
print('-'*10)
print('West Bengal\'s abbreviation is :', states['West Bengal'] )
print('Tamil Nadu\'s abbreviation is: ', states['Tamil Nadu'])

#do it by using the states then cities dict
print('-'*10)
print("Tamil Nadu has:", cities[states['Tamil Nadu']])
print("West Bengal has:", cities[states['West Bengal']])

#print every state abbreviation
print('-'*10)
for state, abbrev in list(states.items()):
  print(f"{abbrev} is abbreviated {state}")

  #print every city in state
  print('-'*10)
  for abbrev, city in list(cities.items()):
    print(f"{state} is abbreviated {abbrev}")
    print(f"and has city {cities[abbrev]}")
    print('-'*10)
    # safety get aabbrviation by state that might not be there
    state = states.get('jharkhand')

    if not state:
      print('Sorry, no Jharkhand')

#get city with default value
city = cities.get('HN', 'Does not exist') 
print(f"The city fo the state HM is : {city}")    

----------
UP state has: Kanpur
AP state has: Visakhapatnam
----------
West Bengal's abbreviation is : WB
Tamil Nadu's abbreviation is:  TN
----------
Tamil Nadu has: Chennai
West Bengal has: Kolkata
----------
UP is abbreviated Uttar Pradesh
----------
Uttar Pradesh is abbreviated UP
and has city Kanpur
----------
Sorry, no Jharkhand
None is abbreviated TN
and has city Chennai
----------
Sorry, no Jharkhand
None is abbreviated WB
and has city Kolkata
----------
Sorry, no Jharkhand
None is abbreviated AP
and has city Visakhapatnam
----------
Sorry, no Jharkhand
None is abbreviated TL
and has city Hyerabad
----------
Sorry, no Jharkhand
AP is abbreviated Andhra Pradesh
----------
Andhra Pradesh is abbreviated UP
and has city Kanpur
----------
Sorry, no Jharkhand
None is abbreviated TN
and has city Chennai
----------
Sorry, no Jharkhand
None is abbreviated WB
and has city Kolkata
----------
Sorry, no Jharkhand
None is abbreviated AP
and has city Visakhapatnam
----------
Sorry, no Jharkha