#Drill #29

<img src="https://drive.google.com/uc?id=109gQ0yPiTdJ6cBQiL1zyKiH2MD5LKTET" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1BhfG7oMzjDH685GbvW2h8b3bKhqkQeSC" width="700">


In [0]:
# CREATING ARRAYS

import numpy as np

# 1-dimensional array
a = np.array([0,1,2,3])
print('1-D array:', a)
print('array of numbers from 0 to 9:', np.arange(10))

print('-'*70)

# 2-dimensional array
b = np.array([[0,1,2],[3,4,5]])
print('2-D array:\n',b)
print('shape of b:', b.shape) #finding the shape of 2-d array b

print('-'*70)

#creating array using random
c= np.random.rand(4) # random samples from a uniform distribution over [0,1]
print('array with random samples:' ,c)

1-D array: [0 1 2 3]
array of numbers from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
----------------------------------------------------------------------
2-D array:
 [[0 1 2]
 [3 4 5]]
shape of b: (2, 3)
----------------------------------------------------------------------
array with random samples: [0.46646    0.8587637  0.31651836 0.13678277]


# Drill #30


<img src="https://drive.google.com/uc?id=1y7J8HlclDc_200W1oYBVtr3l-66B_2hv" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1HPkRafcIsT7vLp8_2rR5blhjblQZJ450" width="600">

In [0]:
# Indexing
import numpy as np
a = np.identity(5)
print('5th row in the 2-d array is:', a[4,:]) #indices begins at 0
a[2,4] = 100; #assigning value in the matrix
print(a)

print('-'*70)

# Slicing
b = np.arange(20)
print(b[1:18:2]) #[starindex: endindex(exclusive) : step]

print('-'*70)

#Basic Operations
a = np.array([1,2,3,4])
print(a+1) # This adds 1 to each element in array a
print(a**2) # squares each element in array a

print('-'*70)

#Matrix Multiplication
c = np.diag([1,2,3,4])
d = np.ones(4) +1
print(c*d)

5th row in the 2-d array is: [0. 0. 0. 0. 1.]
[[  1.   0.   0.   0.   0.]
 [  0.   1.   0.   0.   0.]
 [  0.   0.   1.   0. 100.]
 [  0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   1.]]
----------------------------------------------------------------------
[ 1  3  5  7  9 11 13 15 17]
----------------------------------------------------------------------
[2 3 4 5]
[ 1  4  9 16]
----------------------------------------------------------------------
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


# Drill #31

<img src="https://drive.google.com/uc?id=1MEhGhXS_OC1ZisPbEGQonYcoadzvlKZZ" width="700">
<img src="https://drive.google.com/uc?id=1R24HyNqLMt8j5u3pABKpGlCDnjgUqrX9" width="1000">


# Expected Output
<img src="https://drive.google.com/uc?id=1eqiocySYtWeWuD7NV8plOjubjg0waTRC" width="700">

In [0]:
# comparing arrays
a = np.array([1,2,3,4])
b = np.array([4,2,3,5])
print(a >=b) #element wise comparison
print(np.array_equal(a,b)) #array-wise comparison telling whether a = b or not

print('-'*70)

# Transcendental functions
c= np.arange(1,5)
print(np.sin(c))
print(np.log(c))

print('-'*70)

#Computing Sum
x = np.array([1,2,3,4])
print(np,sum(x)) # Sum all the elements in the array
x = np.array([[1,2,3],[4,5,6]])
print(x.sum(axis=0)) #Sum along column
print(x.sum(axis=1)) #Sum along column

print('-'*70)

#Stiatistics
x = np.array([2,1,3,0,6,2,9,7,4,3])
print('min value:', a.min()) #min/mas value
print('max value:',a.max())
print('min value index:',a.argmin()) #index of minimum element
print('mac value index', a.argmax()) # index of max element
print('mean of x:',x.mean())
print('median of x:',np.median(x))
print('standrad deviation of x:', x.std())

print('-'*70)

#Flattening and Reshaping

a = np.array([[1,2,3],[4,5,6]])
print(a.ravel())#Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned
b = a.reshape((3,2))
print(b)
print(f'shape of a is {a.shape} and shape of b is {b.shape}')

print('-'*70)


#Sorting
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1) #sorting along an axis
print(b)

[False  True  True False]
False
----------------------------------------------------------------------
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
----------------------------------------------------------------------
<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'> 10
[5 7 9]
[ 6 15]
----------------------------------------------------------------------
min value: 1
max value: 4
min value index: 0
mac value index 3
mean of x: 3.7
median of x: 3.0
standrad deviation of x: 2.6851443164195103
----------------------------------------------------------------------
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
shape of a is (2, 3) and shape of b is (3, 2)
----------------------------------------------------------------------
[[4 5 6]
 [2 2 3]]


##Drill #32
<img src="https://drive.google.com/uc?id=11LGUssKKIP6RSXx_fnMWMMMxrOLoLQu2" width="800">

###Expected Output
<img src="https://drive.google.com/uc?id=17R7LrG_YhIIYJKpxKjKsLm22gt4jYtHn" width="600">


In [4]:
import numpy as np
a1 = np.arange(1,7).reshape(2,3)##Array woth numbers 1,2,...,6
a2 = np.arange(1,7).reshape(2,3)*10 ##Array with numbers 10, 20,,...,60

print('a1: \n',a1, '\n a2: \n' , a2)

print('-'*70)

##Now let us stack these arrays horizontally, one to the right and another to the left

a_horizontally_stacked = np.hstack([a1,a1])
print('Horizontal stacking: \n', a_horizontally_stacked)
print('Shape of array after horizonatal stacking:',a_horizontally_stacked.shape)

print('-'*70)

##Now let us stack these arrays vertically, a1 on top and a2 at the bottom
##So shape of arrays after stacking will be [4,3]
##Always be mindful of shape of the arrays. This will help you in debugging.
a_vertically_stacked = np.vstack([a1, a2])

print('Vertical stacking: \n',a_vertically_stacked)
print('Shape of array after vertical stacking:', a_vertically_stacked.shape)

a1: 
 [[1 2 3]
 [4 5 6]] 
 a2: 
 [[10 20 30]
 [40 50 60]]
----------------------------------------------------------------------
Horizontal stacking: 
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
Shape of array after horizonatal stacking: (2, 6)
----------------------------------------------------------------------
Vertical stacking: 
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
Shape of array after vertical stacking: (4, 3)
