General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Write a function to create and return an integer array of shape (5, 2) from a range between 100 to 200 (including 100, excluding 200) such that the difference between consecutive elements is 10.

In [0]:
import numpy as np
def create_integer_array():
  import numpy as np
  a = np.arange(100,200,10).reshape((5,2))
  return a

create_integer_array()


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

### 2
Given a numpy array ```a```, of shape ```(m, n)``` m>=3, n>=3. Write a function to return an array consisting of the elements in 3rd column of ```a``` <br>
Eg., Suppose
``` 
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]    
```
Then 
```
column_3(a) -> [3 6 9]
```

In [21]:
def column_3(a):
  import numpy as np
  a=np.array(a)
  shape_a= a.shape
  a=a.ravel()
  
  if(len(a)>=9):
    a=a.reshape(shape_a)
    return a[:,2]
  else:
    print("you need a column of size atleast 3*3")



array([3, 6, 9])

### 3
Write a function which does the following. Given a numpy array $a$ of shape (m, n), index $i$ and an array $b$ of shape (m, ). Replace the $i_{th}$ column of $a$ with the array $b$  
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]
b = [30, 60, 90]

```    
Then,
```
replace_col(a, 2, b) -> [[1 2 30]
                         [4 5 60]
                         [7 8 90]]
```

In [0]:
def replace_col(a, i, b):
  import numpy as np
  a=np.array(a)
  b=np.array(b)
  
  a[:,i]=b[:]
  return a
  

  

### 4
Write a function which does the following. Given a numpy array $a$ of shape (m, n) and indices $i$, $j$. Return a numpy array which swaps the columns $i$ and $j$ of $a$
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]

swap_cols(a, 0, 2) -> [[3 2 1]
                       [6 5 4]
                       [9 8 7]]
```

In [0]:
def swap_cols(a, i, j):
  import numpy as np
  a=np.array(a)
  
  c=a[:,j]
  c=np.array(c)
  
  a[:,j]=a[:,i]
  a[:,i]=c
  

  return a



  
  

## 5

There are various equivalent ways to define the determinant of a square matrix A, i.e. one with the same number of rows and columns. Perhaps the simplest way to express the determinant is by considering the elements in the top row and the respective minors; starting at the left, multiply the element by the minor, then subtract the product of the next element and its minor, and alternate adding and subtracting such products until all elements in the top row have been exhausted. For example, here is the result for a 4 × 4 matrix: <br>

<img src = "https://drive.google.com/uc?id=1TTljfFZAnOvqgAOiOrv6r4DDRROD-Vph"> <br>

Also, for a 2x2 matrix, this is the formula - <br>
<img src = "https://drive.google.com/uc?id=1H3aFpr1guevWjz4F-XRUQ9eP5TfjVLwu"> <br>

###5.1 Minor
Write a function that does the following. 
Given a square matrix $A$ and an index $i$, find and return the sub-matrix that is the minor corresponding to element at index $i$ of the first row of $A$

In [0]:
def minor(A, i):
  import numpy as np
  A=np.array(A)
  minor_row= np.delete(A,0,0)
  minor_i=np.delete(minor_row,0,1)
  
  return minor_i



###5.2
Given a square matrix $A$, write a function that computes and return the determinant using the formula given above and the helper function that you have defined called ```minor```. <br>
(Do not use the functions to compute determinant which numpy provides built in)

In [0]:
def determinant(A):
  import numpy as np
  A=np.array(A)
  
  if(A.shape==(1)):
    return A[0]
  elif(A.shape==(2,2)):
    det= (A[0,0]*A[1,1])-A[0,1]*A[1,0]
    return det
  else:
    
    for i in range(len(A[1:])):
      det= (-1)**(i)*A[0,0]*determinant(minor(A,i))
      print(minor(A,i))
      
      return det   


